# Generated by Django 5.2.6 on 2025-12-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Plate Number')),
                ('driver_name', models.CharField(max_length=100, verbose_name='Driver Name')),
                ('route', models.CharField(choices=[('NORTH', 'North Route'), ('SOUTH', 'South Route'), ('EAST', 'East Route'), ('WEST', 'West Route'), ('CENTRAL', 'Central Hub')], max_length=50, verbose_name='Route')),
                ('capacity', models.IntegerField(default=50, verbose_name='Seat Capacity')),
                ('current_location', models.CharField(max_length=255, verbose_name='Current Location')),
                ('next_stop', models.CharField(max_length=255, verbose_name='Next Stop')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('occupancy', models.IntegerField(default=0, verbose_name='Current Occupancy')),
                ('eta_minutes', models.IntegerField(default=0, verbose_name='ETA (minutes)')),
                ('traffic_condition', models.CharField(choices=[('Light', 'Light'), ('Normal', 'Normal'), ('Heavy', 'Heavy')], default='Normal', max_length=50, verbose_name='Traffic Condition')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'ordering': ['-created_at'],
            },
        ),
    ]
