# Generated by Django 5.2.7 on 2025-12-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('driver_name', models.CharField(max_length=100)),
                ('route', models.CharField(choices=[('USC-Main', 'University of San Carlos (USC - Main)'), ('CIT-U', 'Cebu Institute of Technology - University (CIT-U)'), ('USJR', 'University of San Jose - Recoletos (USJR)'), ('UP-Cebu', 'University of the Philippines Cebu (UP Cebu - Lahug)'), ('UV', 'University of the Visayas (UV - Colon St.)')], max_length=100)),
                ('current_location', models.CharField(max_length=255)),
                ('next_stop', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(default=50)),
                ('occupancy', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Occupiable', 'Occupiable'), ('Fully Occupied', 'Fully Occupied'), ('Maintenance', 'Maintenance')], default='Occupiable', max_length=50)),
                ('eta_minutes', models.IntegerField(default=0)),
                ('traffic_condition', models.CharField(choices=[('Normal', 'Normal'), ('Heavy', 'Heavy'), ('Light', 'Light')], default='Normal', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
